---
title: "Adding Citations to R Markdown Files"
output:
  html_document:
    theme: readable
    highlight: tango
bibliography: pubs.bibtex
csl: style/apa-single-spaced.csl
nocite: '@*'
---


This is a quick tutorial on integrating a citation management workflow into your R Markdown documents.

Citation management allows you to: 

* Save time by letting your RMD files insert citation information and a bibliography. 
* Change citation styles (from APA to Chicago, for example) with one argument in the YAML header. 

To add citations in RMD you will need the following: 

* A bibTex file: **pubs.bibtex**  
* Citation Style File:  **apa-single-spaced.csl**  

A bibliography will automatically be added to the end of your document. 

Note that you need to add the section on the last line of your RMD file: 

```
# References
```

<br>
<hr>
<br>



### YAML Header

Add your citation database, your preferred formatting (style), and no-citation cases to your YAML header as follows: 

```
---
title: "Adding Citations to R Markdown Files"
output: html_document
bibliography: pubs.bibtex
csl: style/apa-single-spaced.csl
nocite: | 
  @garfield1970citation, @smith1981citation
---
```

Any article that you reference in the document will be automatically added to the bibliography. 

To include articles that you don't cite, include them in the **nocite** section in YAML. 

Here the `@garfield1970citation` and `@smith1981citation` publications will be added to references, even if they were not cited in-text. 

<br>
<hr>
<br>




### Your Bibtext File

Bibtex is an open-source citation convention. Most major academic databases like Google Scholar, Zotero, EndNote, and Web of Science allow you to export citation information for publications in bibtex format. 

Building your bibtex library is easy. Copy bibtex citations from their source and paste the text into your bibtex.pubs file. This file can be edited with a regular text editor.  

Once added, R Markdown will do all of the hard work of formatting references for you!

The first line of each reference serves as the unique ID of the publication. 

```
@article{garfield1955citation,
  title={Citation indexes for science},
  author={Garfield, Eugene},
  journal={Science},
  volume={122},
  number={3159},
  pages={108--111},
  year={1955},
  publisher={JSTOR},
  note={\href{pdf/garfield1955citation.pdf}{PDF}}
}

@book{garfield1979citation,
  title={Citation indexing: Its theory and application in science, technology, and humanities},
  author={Garfield, Eugene and Merton, Robert K},
  volume={8},
  year={1979},
  publisher={Wiley New York},
  note={\href{http://www.garfield.library.upenn.edu/ci/title.pdf}{PDF}}
}

@article{garfield1964use,
  title={The use of citation data in writing the history of science},
  author={Garfield, Eugene and Sher, Irving H and Torpie, Richard J},
  year={1964},
  institution={INSTITUTE FOR SCIENTIFIC INFORMATION INC PHILADELPHIA PA},
  doi={12082},
}

etc...
```

You might check to ensure the IDs are unique. Each ID is auto-generated by combining the author's name, publication year, and first word of the title. In rare cases duplicates can occur, often when there is a working paper version of the article from the same year. 

If you find a duplicate you can just edit the ID to make it unique. 


<br>
<hr>
<br>






### Citation Styles (CSL)

Citation Style (CSL) files are created by journals or academic associations (like the APA), and available for download. 

Add a CSL file to your styles folder if you wish to use the format. 

Chicago and APA styles are common in social sciences, though some journals might require that you use their custom conventions if you are submitting a manuscript for review. 

A repository of CSL styles can be found at https://github.com/citation-style-language/styles ⧉. See also http://zotero.org/styles

A primer on creating and modifying CSL styles can be found at http://citationstyles.org/downloads/primer.html ⧉. 

<br>
<hr>
<br>


### Adding Citations

Add a reference using in-line citations by adding a citation key (e.g. `@smith1981citation`) to the text. 

By default this will add the author last names + year to the text: 

```
Blah blah [see @smith1981citation, pp. 33-35; also @garfield1955citation, ch. 1].

Blah blah [@garfield1970citation, pp. 33-35, 38-39 and *passim*].

Blah blah [@garfield1970citation; @smith1981citation].
```

Blah blah [see @smith1981citation, pp. 33-35; also @garfield1955citation, ch. 1].

Blah blah [@garfield1970citation, pp. 33-35, 38-39 and *passim*].

Blah blah [@garfield1970citation; @smith1981citation].

<br>
<hr>
<br>



### Omitting Author Name

A minus sign (-) before the @ will suppress mention of the author in the citation. This can be useful when the author is already mentioned in the text:

```
Smith [-@smith1981citation] says blah.
```

Smith [-@smith1981citation] says blah.

<br>
<hr>
<br>




### In-Text Citation

You can also write an in-text citation, as follows:

```
@garfield1979citation says blah.

@smith1981citation [p. 33] says blah.
```

@garfield1979citation says blah.

@smith1981citation [p. 33] says blah.

<br>
<hr>
<br>



### Add All Citations to Bibliography

If we do not wish to explicitly state all of the items within the bibliography but would still like to show them in our references, we can use the following syntax anywhere in the document (it's easiest to add it at the end of the document where the actual bibiography will be created):

````
# References 

---
nocite: '@*'
---

````

<br>
<hr>
<br>



### Citation Styles (CSL)

A primer on creating and modifying CSL styles can be found at http://citationstyles.org/downloads/primer.html ⧉. A repository of CSL styles can be found at https://github.com/citation-style-language/styles ⧉. See also http://zotero.org/styles

<br>
<hr>
<br>


### Linking to Publications 

Add a hyperlink to a PDF of the pub by adding a field at the end of the Citation Style Layout (CSL) file. 

In your bibtex file create a new field **note**. Note is a defined field in bibtex already, but we can repurpose it to create the publication link.  


```
@book{garfield1979citation,
  title={Citation indexing: Its theory and application in science, technology, and humanities},
  author={Garfield, Eugene and Merton, Robert K},
  volume={8},
  year={1979},
  publisher={Wiley New York},
  note={\href{http://www.garfield.library.upenn.edu/ci/title.pdf}{PDF}}
}
```

To add the hyperlink text instead of printing the URL directly you need to use the convention `{\href{http://www.some.url/}{PDF}}`
  
Next, add the new variable (`<text variable="note"/>`) at the end of the bibliography section of the CSL file. 


```
...
<bibliography>
  <sort>
    <key macro="author"/>
    <key macro="issued-year"/>
    <key variable="title"/>
  </sort>
  <layout suffix="." delimiter=", ">
    <group delimiter=". ">
      <text macro="author"/>
      <text macro="issued-year"/>
      <text variable="title"/>
      <text variable="container-title"/>
    </group>
    <group>
      <text variable="volume"/>
      <text variable="issue" prefix="(" suffix=")"/>
    </group>
    <text variable="page"/>
    <text variable="note"/>
  </layout>
</bibliography>
```

<br>
<hr>
<br>


# References 


